export const AG_GRID_LOCALE_TR = {
    // Set Filter
    selectAll: '(Tümünü Seç)',
    selectAllSearchResults: '(Tüm Arama Sonuçlarını Seç)',
    searchOoo: 'Arama...',
    blanks: '(Boş)',
    noMatches: 'Eşleşme Yok',

    // Number Filter & Text Filter
    filterOoo: 'Filtre...',
    equals: 'Eşittir',
    notEqual: 'Eşit Değilse',
    blank: 'Boş',
    notBlank: 'Boş Olmayan',
    empty: 'Birini Seç',

    // Number Filter
    lessThan: 'Küçüktür',
    greaterThan: 'Büyüktür',
    lessThanOrEqual: 'Küçük eşit',
    greaterThanOrEqual: 'Büyük eşit',
    inRange: 'Aralık',
    inRangeStart: 'itibaren',
    inRangeEnd: 'kadar',

    // Text Filter
    contains: 'İçeriyorsa',
    notContains: 'İçermiyorsa',
    startsWith: 'Başlıyorsa',
    endsWith: 'Bitiyorsa',

    // Date Filter
    dateFormatOoo: 'dd.mm.yyyy',

    // Filter Conditions
    andCondition: 'VE',
    orCondition: 'VEYA',

    // Filter Buttons
    applyFilter: 'Filtrele',
    resetFilter: 'Filtreleri Sıfırla',
    clearFilter: 'Filtreleri Temizle',
    cancelFilter: 'Filtreleri İptal Et',

    // Filter Titles
    textFilter: 'Metin Filtresi',
    numberFilter: 'Sayı Filtresi',
    dateFilter: 'Tarih Filtresi',
    setFilter: 'Filtre Ayarla',

    // Side Bar
    columns: 'Sütunlar',
    filters: 'Filtreler',

    // columns tool panel
    pivotMode: 'Pivot Mod',
    groups: 'Satır Grupları',
    rowGroupColumnsEmptyMessage: 'Satır gruplarını ayarlamak için buraya sürükleyin',
    values: 'Değerler',
    valueColumnsEmptyMessage: 'Birleştirmek için buraya sürükleyin',
    pivots: 'Sütun Etiketleri',
    pivotColumnsEmptyMessage: 'Sütun etiketlerini ayarlamak için buraya sürükleyin',

    // Header of the Default Group Column
    group: 'Grup',

    // Row Drag
    rowDragRows:'satırlar',

    // Other
    loadingOoo: 'Yükleniyor...',
    noRowsToShow: 'Gösterilecek Satır Yok',
    enabled: 'Etkinleştirilmiş',

    // Menu
    pinColumn: 'Sütunu Sabitle',
    pinLeft: 'Sola Sabitle',
    pinRight: 'Sağa Sabitle',
    noPin: 'Sabitleme',
    valueAggregation: 'Değer Toplama',
    autosizeThiscolumn: 'Bu Sütunu Otomatik Boyutlandır',
    autosizeAllColumns: 'Tüm Sütunları Otomatik Boyutlandır',
    groupBy: 'Grupla',
    ungroupBy: 'Gruplamayı Kaldır',
    addToValues: 'Değerlere ${variable} ekleyin',
    removeFromValues: 'Değerlerden ${variable} kaldırın',
    addToLabels: 'Add ${variable} to labels',
    removeFromLabels: 'Etiketlere ${variable} ekleyin',
    resetColumns: 'Sütunları Sıfırla',
    expandAll: 'Hepsini Genişlet',
    collapseAll: 'Hepsini Kapat',
    copy: 'Kopyala',
    ctrlC: 'Ctrl+C',
    copyWithHeaders: 'Başlıklarla Kopyala',
    copyWithGroupHeaders: 'Grup Başlıklarıyla Kopyala',
    paste: 'Yapıştır',
    ctrlV: 'Ctrl+V',
    export: 'Dışa Aktar',
    csvExport: 'CSV\'e Aktar',
    excelExport: 'Excel\'e Aktar',

    // Enterprise Menu Aggregation and Status Bar
    sum: 'Toplam',
    min: 'Min',
    max: 'Max',
    none: 'Hiçbiri',
    count: 'Sayı',
    avg: 'Ortalama',
    filteredRows: 'Filtrelendi',
    selectedRows: 'Seçildi',
    totalRows: 'Toplam Satır',
    totalAndFilteredRows: 'Satırlar',
    more: 'Daha',
    to: 'den',
    of: '-',
    page: 'Sayfa',
    nextPage: 'Sonraki Sayfa',
    lastPage: 'Son Sayfa',
    firstPage: 'İlk Sayfa',
    previousPage: 'Önceki sayfa',

    // Pivoting
    pivotColumnGroupTotals: 'Toplam',

    // Enterprise Menu (Charts)
    pivotChartAndPivotMode: 'Pivot Grafik ve Pivot Modu',
    pivotChart: 'Pivot Grafik',
    chartRange: 'Grafik Aralığı',

    columnChart: 'Sütun',
    groupedColumn: 'Gruplandırılmış',
    stackedColumn: 'Yığılmış',
    normalizedColumn: '100% Yığılmış',

    barChart: 'Çubuk',
    groupedBar: 'Gruplandırılmış',
    stackedBar: 'Yığılmış',
    normalizedBar: '100% Yığılmış',

    pieChart: 'Pie',
    pie: 'Pie',
    doughnut: 'Donut',

    line: 'Çizgi',

    xyChart: 'X Y (Dağılım)',
    scatter: 'Dağılım',
    bubble: 'Baloncuk',

    areaChart: 'Alan',
    area: 'Alan',
    stackedArea: 'Yığılmış',
    normalizedArea: '100% Yığılmış',

    histogramChart: 'Histogram',

    combinationChart: 'Kombinasyon',
    columnLineCombo: 'Sütun & Çizgi',
    AreaColumnCombo: 'Alan & Sütun',

    // Charts
    pivotChartTitle: 'Pivot Grafik',
    rangeChartTitle: 'Grafik Aralığı',
    settings: 'Ayarlar',
    data: 'Veri',
    format: 'Format',
    categories: 'Karegoriler',
    defaultCategory: '(Hiçbiri)',
    series: 'Diziler',
    xyValues: 'X Y Değerler',
    paired: 'Eşleştirilmiş mod',
    axis: 'Eksen',
    navigator: 'Gezgin',
    color: 'Renk',
    thickness: 'Kalınlık',
    xType: 'X Tip',
    automatic: 'Otomatik',
    category: 'Kategori',
    number: 'Sayı',
    time: 'Zaman',
    autoRotate: 'Otomatik Döndürme',
    xRotation: 'X Döndürme',
    yRotation: 'Y Döndürme',
    ticks: 'Ticks',
    width: 'Genişlik',
    height: 'Yükseklik',
    length: 'Uzunluk',
    padding: 'Padding',
    spacing: 'Aralık',
    chart: 'Grafik',
    title: 'Başlık',
    titlePlaceholder: 'Grafik başlığı - düzenlemek için çift tıklayın',
    background: 'Arkaplan',
    font: 'Yazı tipi',
    top: 'Üst',
    right: 'Sağ',
    bottom: 'Alt',
    left: 'Sol',
    labels: 'Etiketler',
    size: 'Boyut',
    minSize: 'Minimum Boyut',
    maxSize: 'Maksimum Boyut',
    legend: 'Legend',
    position: 'Position',
    markerSize: 'İşaretleyici Boyutu',
    markerStroke: 'İşaretleyici Çizgisi',
    markerPadding: 'İşaretleyici İç Boşluğu',
    itemSpacing: 'İtem Boşluk ',
    itemPaddingX: 'İtem İç Boşluk X',
    itemPaddingY: 'İtem İç Boşluk Y',
    layoutHorizontalSpacing: 'Yatay Boşluk',
    layoutVerticalSpacing: 'Dikey Boşluk',
    strokeWidth: 'Çizgi Genişliği',
    offset: 'Girinti',
    offsets: 'Girintiler',
    tooltips: 'İpucu Kutusu',
    callout: 'Çağırmak',
    markers: 'İşaretleyiciler',
    shadow: 'Gölge',
    blur: 'Bulanık',
    xOffset: 'X Girintisi',
    yOffset: 'Y Girintisi',
    lineWidth: 'Çizgi Genişliği',
    normal: 'Normal',
    bold: 'Kalın',
    italic: 'Eğik',
    boldItalic: 'Kalın Eğik',
    predefined: 'Ön Tanımlı',
    fillOpacity: 'Dolgu Opaklığı',
    strokeOpacity: 'Çizgi Opaklığı',
    histogramBinCount: 'Kutu Sayısı',
    columnGroup: 'Sütun',
    barGroup: 'Çubuk',
    pieGroup: 'Pasta',
    lineGroup: 'Çizgi',
    scatterGroup: 'X Y (Dağılım)',
    areaGroup: 'Alan',
    histogramGroup: 'Histogram',
    combinationGroup: 'Kombinasyon',
    groupedColumnTooltip: 'Gruplandırılmış',
    stackedColumnTooltip: 'Yığılmış',
    normalizedColumnTooltip: '100% Yığılmış',
    groupedBarTooltip: 'Gruplandırılmış',
    stackedBarTooltip: 'Yığılmış',
    normalizedBarTooltip: '100% Yığılmış',
    pieTooltip: 'Pasta',
    doughnutTooltip: 'Donut',
    lineTooltip: 'Çizgi',
    groupedAreaTooltip: 'Alan',
    stackedAreaTooltip: 'Yığılmış',
    normalizedAreaTooltip: '100% Yığılmış',
    scatterTooltip: 'Dağılım',
    bubbleTooltip: 'Baloncuk',
    histogramTooltip: 'Histogram',
    columnLineComboTooltip: 'Sütun & Çizgi',
    areaColumnComboTooltip: 'Alan & Sütun',
    customComboTooltip: 'Özel Kombinasyon',
    noDataToChart: 'Çizelgelendirilecek veri yok.',
    pivotChartRequiresPivotMode: 'Pivot Grafik, Pivot Modunun etkinleştirilmesini gerektirir.',
    chartSettingsToolbarTooltip: 'Menü',
    chartLinkToolbarTooltip: 'Izgaraya Bağlanmış',
    chartUnlinkToolbarTooltip: 'Izgaraya Bağlanmamış',
    chartDownloadToolbarTooltip: 'Grafiği İndir',
    seriesChartType: 'Dizi Grafik Tipi',
    seriesType: 'Dizi Tipi',
    secondaryAxis: 'İkincil Eksen',

    // ARIA
    ariaChecked: 'Seçili',
    ariaColumn: 'Sütun',
    ariaColumnGroup: 'Sütun Grubu',
    ariaColumnList: 'Sütun Listesi',
    ariaColumnSelectAll: 'Tüm Sütunları Seç\'i Aç',
    ariaDateFilterInput: 'Tarih Filtresi Girişi',
    ariaDefaultListName: 'Liste',
    ariaFilterColumnsInput: 'Filtre Sütunları Girişi',
    ariaFilterFromValue: 'Değerden Filtrele',
    ariaFilterInput: 'Filtre Girişi',
    ariaFilterList: 'Filtre Listesi',
    ariaFilterToValue: 'Değere Filtrele',
    ariaFilterValue: 'Filtre Değeri',
    ariaFilteringOperator: 'Filtreleme Operatörü',
    ariaHidden: 'gizle',
    ariaIndeterminate:'ortanca',
    ariaInputEditor: 'Giriş Editörü',
    ariaMenuColumn: 'Sütun menüsünü açmak için CTRL ENTER\'a basın.',
    ariaRowDeselect: 'Bu satırın seçimini kaldırmak için SPACE tuşuna basın',
    ariaRowSelectAll: 'Tüm satır seçimini değiştirmek için SPACE tuşuna basın',
    ariaRowToggleSelection: 'Satır seçimini değiştirmek için SPACE tuşuna basın',
    ariaRowSelect: 'Bu satırı seçmek için SPACE tuşuna basın',
    ariaSearch: 'Arama',
    ariaSortableColumn: 'Sıralamak için ENTER\'a basın',
    ariaToggleVisibility: 'Görünürlüğü değiştirmek için SPACE tuşuna basın',
    ariaUnchecked: 'seçilmemiş',
    ariaVisible: 'görünür',
    ariaSearchFilterValues: 'Arama Filtresi Değerleri',

    // ARIA Labels for Drop Zones

    ariaRowGroupDropZonePanelLabel: 'Satır Grupları',
    ariaValuesDropZonePanelLabel: 'Değerler',
    ariaPivotDropZonePanelLabel: 'Sütun Etiketleri',
    ariaDropZoneColumnComponentDescription: 'Kaldırmak için DELETE\'e basın',
    ariaDropZoneColumnValueItemDescription: 'Toplama türünü değiştirmek için ENTER\'a basın',

    // ARIA Labels for Dialogs
    ariaLabelColumnMenu: 'Sütun Menusü',
    ariaLabelCellEditor: 'Hücre Editörü',
    ariaLabelDialog: 'Dialog',
    ariaLabelSelectField: 'Alan Seç',
    ariaLabelTooltip: 'İpucu Kutusu',
    ariaLabelContextMenu: 'Sağ Menü',
    ariaLabelSubMenu: 'Alt Menü',
    ariaLabelAggregationFunction: 'Toplama Fonksiyonu',

    // Number Format (Status Bar, Pagination Panel)
    thousandSeparator: ',',
    decimalSeparator: '.'

}
